"use client";

import { AppShell } from "@/components/app-shell";
import { PageHeader, PrimaryButton } from "@/components/ui";
import { loadLocal, saveLocal } from "@/lib/local-store";
import { Bell, BellRing, ChevronRight, Download, Eraser, UserRound, Waves } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getPushState, sendTestNotification, subscribeToPush } from "@/lib/push-client";
import { saveProfile } from "@/lib/profile-client";

export default function SettingsPage() {
  const [name, setName] = useState("寶貝"); const [goal, setGoal] = useState(2000); const [saved, setSaved] = useState(false); const [subscribed, setSubscribed] = useState(false); const [permission, setPermission] = useState("檢查中"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setName(loadLocal("hydralove-partner", "寶貝")); setGoal(loadLocal("hydralove-goal", 2000)); setPermission(typeof Notification === "undefined" ? "未支援" : Notification.permission === "granted" ? "已允許" : "尚未允許"); getPushState().then(setSubscribed).catch(() => setSubscribed(false)); }, 0); return () => window.clearTimeout(timer); }, []);
  const save = async () => { setBusy(true); setNotice(""); try { saveLocal("hydralove-partner", name); saveLocal("hydralove-goal", goal); await saveProfile(name, goal); setSaved(true); setTimeout(() => setSaved(false), 1800); } catch (error) { setNotice(error instanceof Error ? error.message : "設定儲存失敗"); } finally { setBusy(false); } };
  const clear = () => { if (confirm("確定清除所有本機資料？")) { Object.keys(localStorage).filter(key => key.startsWith("hydralove-")).forEach(key => localStorage.removeItem(key)); location.reload(); } };
  const enable = async () => { setBusy(true); setNotice(""); try { await subscribeToPush(); setSubscribed(true); setPermission("已允許"); setNotice("通知已成功啟用。"); } catch (error) { setNotice(error instanceof Error ? error.message : "通知設定失敗"); } finally { setBusy(false); } };
  const test = async () => { setBusy(true); setNotice(""); try { await sendTestNotification(); setNotice("測試通知已送出。"); } catch (error) { setNotice(error instanceof Error ? error.message : "測試通知失敗"); } finally { setBusy(false); } };
  return <AppShell><PageHeader title="設定" /><div className="space-y-5 px-5"><section className="card p-5"><label className="block text-sm font-bold"><span className="mb-2 flex items-center gap-2"><UserRound size={17} className="text-[var(--primary)]" />伴侶名稱</span><input value={name} onChange={e => setName(e.target.value)} className="focus-ring w-full rounded-2xl border border-[var(--border)] bg-[var(--background)] px-4 py-3.5" /></label><label className="mt-4 block text-sm font-bold"><span className="mb-2 flex items-center gap-2"><Waves size={17} className="text-[var(--primary)]" />每日飲水目標</span><div className="relative"><input type="number" min={500} step={100} value={goal} onChange={e => setGoal(Number(e.target.value))} className="focus-ring w-full rounded-2xl border border-[var(--border)] bg-[var(--background)] px-4 py-3.5 pr-14" /><span className="absolute right-4 top-3.5 text-sm font-bold text-[var(--muted)]">ml</span></div></label><PrimaryButton className="mt-5" onClick={save}>{saved ? "已儲存" : "儲存設定"}</PrimaryButton></section><section><h2 className="mb-3 text-sm font-extrabold text-[var(--muted)]">通知與安裝</h2><div className="card divide-y divide-[var(--border)] overflow-hidden"><SettingRow icon={<Bell />} title="通知權限" value={permission} /><SettingRow icon={<BellRing />} title="Push 訂閱" value={subscribed ? "已連線" : "尚未設定"} /><Link href="/setup" className="flex min-h-16 items-center gap-3 px-4"><span className="grid size-10 place-items-center rounded-2xl bg-[#E4F7F9] text-[var(--primary-dark)]"><Download size={19} /></span><div className="flex-1"><b className="text-sm">安裝與通知教學</b><p className="text-xs text-[var(--muted)]">Safari 加至主畫面</p></div><ChevronRight size={18} className="text-slate-400" /></Link></div></section>{notice && <p role="status" className="rounded-2xl border border-[var(--border)] bg-white p-3 text-sm font-semibold leading-5">{notice}</p>}<div className="grid grid-cols-2 gap-3"><button disabled={busy} onClick={enable} className="focus-ring tap rounded-2xl border border-[var(--primary)] bg-white px-3 text-sm font-bold text-[var(--primary-dark)]">啟用通知</button><PrimaryButton disabled={busy || !subscribed} onClick={test}>測試通知</PrimaryButton></div><button onClick={clear} className="focus-ring tap flex w-full items-center justify-center gap-2 rounded-2xl border border-[#FFD7D2] bg-white font-bold text-[var(--accent)]"><Eraser size={17} />清除本機資料</button><p className="px-2 text-center text-xs leading-5 text-[var(--muted)]">HydraLove 使用 Web Push 發送通知，不會自動傳送 iMessage 或 WhatsApp。</p></div></AppShell>;
}

function SettingRow({ icon, title, value }: { icon: React.ReactNode; title: string; value: string }) { return <div className="flex min-h-16 items-center gap-3 px-4"><span className="grid size-10 place-items-center rounded-2xl bg-[#E4F7F9] text-[var(--primary-dark)] [&>svg]:size-[19px]">{icon}</span><b className="flex-1 text-sm">{title}</b><span className="text-xs font-bold text-[var(--muted)]">{value}</span></div>; }
